version: "3.9"
services:
  go:
    container_name: go-ws
    tty: true
    build: .
    ports:
      - 8000:8080
    depends_on:
      - database
    networks:
      - learning
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    container_name: pg
    ports:
      - '1234:5432'
    volumes:
      - ./pg_data:/var/lib/postgres/data
    networks:
      - learning
volumes:
  pg_data:
networks:
  learning:
    driver: bridge
