version: "3.9"
services:
  go:
    container_name: go-ws
    tty: true
    build: .
    ports:
      - 8000:8080
    depends_on:
      - database
    networks:
      - net_ws
  pg_docker:
    container_name: pg
    image: postgres:latest
    environment:
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pg_data/
    ports:
      - '1234:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - net_ws
volumes:
  pg_data:
    name: ${VOLUME_ID}
networks:
  net_ws:
    driver: bridge
